baseURL = 'https://evsky.art/'
languageCode = 'en-us'
title = "Evsky's blog"
theme = 'paperesque'
copyright = "© 2023 Evsky"
staticDir = ['static']

[markup.goldmark.renderer]
  unsafe = true # Allow HTML in md files

[[params.topmenu]]
  name = "blog"
  url = "posts/"

[[params.topmenu]]
  name = "tags"
  url = "tags/"

#[[params.topmenu]]
#  name = "about"
#  url = "about/"


